### ISSUE TITLE
Wrong quantities on the laser shredding overview pdf

### ISSUE THREAD

**Issue by sylvainv** [hakkens/precious-plastic-kit#1]
I submitted my request to various laser companies and they think the order is too small. I just noticed the overview actually mentions the quantity of every single piece is 1, while each individual 3mm, 5mm and 6mm pdf shows each of them the correct quantity.

I think to speed up contacting laser cut services companies it would be great to have the blue prints provided with the right quantities.

Great project btw!

**Comment by davehakkens** [comment]
Thanks for mentioning, makes sense. Are you able to create that file? We will add it!

**Comment by sylvainv** [comment]
I haven't found a cheap version of AutoCad so far, so I cannot edit the file. Also I would like to translate the files into Chinese. Is there any translation plan for the blueprints ?

**Comment by davehakkens** [comment]
cool!
Have a look at this topic, just started it :)
https://davehakkens.nl/community/forums/topic/translating-our-content/



Op woensdag 20 april 2016, om 18:05 heeft Sylvain het volgende geschreven:

**Comment by cowanml** [comment]
still not quite right...
Should be Qty=2 for "Shredding Sideplate Lasercutted" and, with the holes for the fixed knives, Qty=2 for "Shredding Bracket Top+Left / Bottom+Right" and Qty=2 for "Shredding Bracket Top+Right / Bottom+Left".

I was looking into fixing this, and some issues with "Shredder 2.1 .PDF" (missing hopper mounting hole on top right of isometric view and inconsistent holes/slots for the sieve retaining rods between the isometric and face on views), but the workflow for the .pdf's isn't clear to me.  Is there a source document for the pdf's somewhere?  Or do you use some software to edit them directly?  Would be cool to have a continuous integration task that automatically updated them when cad drawings were updated! :)
