### ISSUE TITLE
v3.1

### ISSUE THREAD

**Issue by tx4x** [hakkens/precious-plastic-kit#14]
there are some urgent fixes to do : 

**shredder**
- needs 28 mm hexbar, 27 mm is very hard to get in most countries i checked, also add warnings that the drive shaft may brake (as it happened to some)
- material bill :  add a non-scrap yard version using new parts, also hidden parts are missing : nuts, cables, breaker, switch
- links: links to forum posts, motor guide/experience

**extrusion**
- add motor details and eventually sources in europe (at least)
- realistic material bill when buying new

**injection**
- realistic material bill when buying new

@davehakkens : i can do that this week, question is you actually merge it (my last PR didn't went live)
g

**Comment by tx4x** [comment]
of course driveshaft exit should be 25 mm diameter, only then you could add a stronger motor.

**Comment by davehakkens** [comment]
1. I'm up for adding a realistic bill of materials for scrap & new. Showing both options for all machines.
2. I wouldn't change the hexbar dimensions. Some countries 27 is easier then 28. Also wouldn't change without properly testing since it also means changing the laser-cut blades. That said we could add a remark that says people can change themselves or adapt a few dimensions to the hexbar they find.
3. adding links is useful.

We only merge a pull request if it's documented properly and the information is accurate..
*Other merge is on the list for our next platform-update, we only update occasionally

**Comment by tx4x** [comment]
ok, no problem. we tested 28 mm and 32 mm successfully. btmetz in forum too.
In germany, spain, and france however 27 mm is near impossible. are you sure about that some countries it's easier to get 27 mm ? i'd love to know where to get those anyways :-)

ok then, let's try piece by piece.  
g

**Comment by tx4x** [comment]
@davehakkens one thing: what about you open an excel sheet on google, so we can collect those prices with the community ? i have enough data for USA & Europe. I know 2 people who can assist here with Asia and India.

**Comment by tx4x** [comment]
what you mean actually by 'if it's documented properly and the information is accurate..' ? not to what issue your referring.

testing: we and other machine builders have tested 28 mm and 32 hexbars, just looking at that 20 mm driveshaft makes an ordinary machinist laugh :-) no offense, but we have doubts that you have any qualifications and professional background in that matters ;-)

however, 
1. i compile now the material bills first
2. update and store the CAD files in v3.1 - 28/32 mm hexbar, together with the new exported laser files

**Comment by davehakkens** [comment]
with documented properly I mean its done clear and clean. It easily becomes a mess in an open-source projects. Specially the download kit with many people contributing and different versions being released. Proper documentation is crucial for us so its key to stick to our current framework and way of releasing things.

Don't want to demotivate you here, but i'd suggest to give it a good think before you start this process. You seem the disagree with many of our decisions and become frustrated. I'd suggest to think twice before you throw your energy into it

**Comment by tx4x** [comment]
right, yeah no worry. we have some capacities here, full-time, that are just a few modifications to do. updating cad, laser files, blue-prints isn't exactly much work. also material bills are now pretty clear to us.

I think adding safety, clarity and completeness worth the effort, especially if it can prevent users from failing or having bad surprises on their way.

**Comment by tx4x** [comment]
so, we spoke with a former machinist (german: Dipl. Ing. Maschienenbau), he also said, that 20 mm shaft exit is below 'soll', considering 2-3 Kw torque. That would explain the various reported drive shaft breaks.

so the PRs will be in this order : 

1. PR - hexbar - 28 mm, placed in build/Shredder/Blueprints/00_laser_files_28_mm (2.2 + Kw motors)
2. PR - hexbar - 32 mm, placed in build/Shredder/Blueprints/00_laser_files_32_mm (4Kw motors)

3. PR - material - bill - new components - eu-prices, complete list of parts
4. PR - material - bill - new components - asia-prices, complete list of parts

5. PR - meta - shredder : tips, links, notes, warnings, community feedback, posts

6. PR - extrusion : motor details, links and community feedback

We roll out this updates in the next weeks.

**Comment by tx4x** [comment]
if you like we can put the arbor [injection press into the package](https://www.instagram.com/p/Bt-1GU8hoAg/), complete as the others. we don't mind license & credits.. quite a powerful and successful machine.
